# Generated by Django 5.1.4 on 2025-01-03 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
        ('github_app', '0003_push_delivery_alter_push_payload'),
        ('runner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='head_commit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='github.commit'),
        ),
        migrations.AlterField(
            model_name='task',
            name='push',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='github_app.push'),
        ),
    ]
