# Generated by Django 5.1.6 on 2025-03-12 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('github', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('active', models.BooleanField()),
                ('head_commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github.commit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField()),
                ('result', models.CharField(choices=[('W', 'Win'), ('L', 'Loss'), ('D', 'Draw')], max_length=1)),
                ('rating_change', models.IntegerField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='y2025_winter.bot')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='y2025_winter.bot')),
            ],
        ),
    ]
