# Generated by Django 5.0.7 on 2024-07-26 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.DateTimeField(auto_now_add=True)),
                ('discord_user_id', models.BigIntegerField()),
                ('discord_guild_id', models.BigIntegerField()),
                ('discord_channel_id', models.BigIntegerField()),
                ('discord_message_id', models.BigIntegerField()),
                ('content', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonymous_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
