# Generated by Django 5.0.7 on 2024-07-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousmessage',
            name='undid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
