# Generated by Django 4.2.7 on 2023-11-08 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_webhook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created']},
        ),
    ]
