# Generated by Django 5.0.7 on 2024-07-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Push',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.DateTimeField(auto_now_add=True)),
                ('event', models.JSONField(unique=True)),
            ],
        ),
    ]
