# Generated by Django 5.0.7 on 2024-09-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_app', '0002_rename_event_push_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='push',
            name='delivery',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='push',
            name='payload',
            field=models.JSONField(),
        ),
    ]
