# Generated by Django 5.0.6 on 2024-07-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='discord_role_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
