# Generated by Django 5.0.7 on 2024-08-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='num_lecture_sections',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
