# Generated by Django 5.0.7 on 2024-08-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_offering_num_lecture_sections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='discord_role_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
