# Generated by Django 5.0.7 on 2024-08-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_institution_discord_role_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='discord_role_id',
            new_name='verified_discord_role_id',
        ),
        migrations.AddField(
            model_name='institution',
            name='faculty_discord_role_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='first_year_discord_role_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='fourth_year_discord_role_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='grad_student_discord_role_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='second_year_discord_role_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='third_year_discord_role_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
