# Generated by Django 5.0.7 on 2024-09-13 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_assignmenttask_task_assignmenttask_user'),
        ('runner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='runner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='runner.runner'),
        ),
    ]
