# Generated by Django 5.0.7 on 2024-11-07 16:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_team_teammember_team_unique_team_name_per_offering'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferingTeamsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_team_size', models.IntegerField(default=3)),
                ('formation_deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('show_group_members', models.BooleanField(default=True)),
                ('allow_custom_names', models.BooleanField(default=False)),
                ('offering', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.offering')),
            ],
        ),
    ]
