# Generated by Django 5.1.4 on 2025-02-25 18:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0014_offeringteamssettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='github_team_slug',
            field=models.CharField(default='default-student-team', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField()),
                (
                    "content_viewable_after_submission",
                    models.BooleanField(default=False),
                ),
                ("visible_at", models.DateTimeField()),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="courses.offering",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField()),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_submissions",
                        to="courses.assessment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckboxQuestion",
            fields=[
                ("prompt", models.TextField()),
                ("points", models.PositiveIntegerField(default=1)),
                ("order", models.PositiveIntegerField()),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("options", models.JSONField()),
                ("correct_option_indices", models.JSONField(null=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkbox_questions",
                        to="courses.assessment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckboxAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_updated_at", models.DateTimeField()),
                ("selected_answer_indices", models.JSONField(null=True)),
                (
                    "assessment_submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkbox_answers",
                        to="courses.assessmentsubmission",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="courses.checkboxquestion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CodingQuestion",
            fields=[
                ("prompt", models.TextField()),
                ("points", models.PositiveIntegerField(default=1)),
                ("order", models.PositiveIntegerField()),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("starter_code", models.TextField(blank=True, null=True)),
                (
                    "programming_language",
                    models.CharField(
                        choices=[("C_PP", "C++"), ("C", "C"), ("PYTHON", "Python")],
                        max_length=6,
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_questions",
                        to="courses.assessment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CodingAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_updated_at", models.DateTimeField()),
                ("solution", models.TextField()),
                (
                    "assessment_submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_question_answers",
                        to="courses.assessmentsubmission",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="courses.codingquestion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MultipleChoiceQuestion",
            fields=[
                ("prompt", models.TextField()),
                ("points", models.PositiveIntegerField(default=1)),
                ("order", models.PositiveIntegerField()),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("options", models.JSONField()),
                ("correct_option_index", models.PositiveIntegerField()),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multiple_choice_questions",
                        to="courses.assessment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MultipleChoiceAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_updated_at", models.DateTimeField()),
                ("selected_answer_index", models.PositiveIntegerField()),
                (
                    "assessment_submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multiple_choice_answers",
                        to="courses.assessmentsubmission",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="courses.multiplechoicequestion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WrittenResponseQuestion",
            fields=[
                ("prompt", models.TextField()),
                ("points", models.PositiveIntegerField(default=1)),
                ("order", models.PositiveIntegerField()),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("max_length", models.PositiveIntegerField(default=200, null=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="written_response_questions",
                        to="courses.assessment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WrittenResponseAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_updated_at", models.DateTimeField()),
                ("response", models.TextField()),
                (
                    "assessment_submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="written_response_answers",
                        to="courses.assessmentsubmission",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="courses.writtenresponsequestion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="checkboxquestion",
            constraint=models.UniqueConstraint(
                fields=("assessment", "order"), name="unique_order_checkbox_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="codingquestion",
            constraint=models.UniqueConstraint(
                fields=("assessment", "order"), name="unique_order_coding_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="multiplechoicequestion",
            constraint=models.UniqueConstraint(
                fields=("assessment", "order"),
                name="unique_order_multiple_choice_question",
            ),
        ),
        migrations.AddConstraint(
            model_name="writtenresponsequestion",
            constraint=models.UniqueConstraint(
                fields=("assessment", "order"),
                name="unique_order_written_response_question",
            ),
        ),
    ]
