# Generated by Django 5.0.7 on 2024-09-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0014_remove_team_members_alter_enrollment_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
