# Generated by Django 5.0.7 on 2024-11-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_offeringteamssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='github_team_slug',
            field=models.CharField(default='default-student-team', max_length=255),
            preserve_default=False,
        ),
    ]
