# Generated by Django 5.0.7 on 2024-11-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_assessment_assessmentsubmission_checkboxquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='slug',
            field=models.SlugField(default='default'),
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('slug', 'offering')},
        ),
    ]
