# Generated by Django 5.1.4 on 2025-01-02 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_assignmentgrade'),
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='runner_repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offering_runner', to='github.repository'),
        ),
    ]
