# Generated by Django 5.0.7 on 2025-01-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0015_exam_codingquestion_checkboxquestion_examsubmission_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="slug",
            field=models.SlugField(),
        ),
    ]
