# Generated by Django 5.0.7 on 2024-11-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_assessment_slug_alter_assessment_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'verbose_name': 'Assessment', 'verbose_name_plural': 'Assessments'},
        ),
        migrations.RemoveField(
            model_name='checkboxanswer',
            name='assessment_submission',
        ),
        migrations.RemoveField(
            model_name='codinganswer',
            name='assessment_submission',
        ),
        migrations.RemoveField(
            model_name='multiplechoiceanswer',
            name='assessment_submission',
        ),
        migrations.RemoveField(
            model_name='writtenresponseanswer',
            name='assessment_submission',
        ),
    ]
