# Generated by Django 5.0.7 on 2024-11-28 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_assessment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkboxanswer',
            name='assessment_submission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checkbox_answers', to='courses.assessmentsubmission'),
        ),
        migrations.AddField(
            model_name='codinganswer',
            name='assessment_submission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coding_question_answers', to='courses.assessmentsubmission'),
        ),
        migrations.AddField(
            model_name='multiplechoiceanswer',
            name='assessment_submission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_answers', to='courses.assessmentsubmission'),
        ),
        migrations.AddField(
            model_name='writtenresponseanswer',
            name='assessment_submission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='written_response_answers', to='courses.assessmentsubmission'),
        ),
    ]
