# Generated by Django 5.1.4 on 2025-03-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_codinganswer_codingquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkboxanswer',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codinganswer',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoiceanswer',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writtenresponseanswer',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
