# Generated by Django 5.1.4 on 2025-01-20 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_codingquestion_alter_enrollment_student_repo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeringteamssettings',
            name='allow_custom_names',
        ),
        migrations.RemoveField(
            model_name='offeringteamssettings',
            name='show_group_members',
        ),
        migrations.AlterField(
            model_name='offeringteamssettings',
            name='formation_deadline',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 20, 20, 43, 44, 113000, tzinfo=datetime.timezone.utc)),
        ),
    ]
