# Generated by Django 5.1.4 on 2025-03-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_checkboxanswer_grade_codinganswer_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkboxanswer',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codinganswer',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoiceanswer',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writtenresponseanswer',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
