# Generated by Django 5.1.4 on 2025-02-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_quizsubmission_grade_quizsubmission_graded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
