# Generated by Django 5.1.4 on 2025-01-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_assignment_overall_total_assignment_private_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_private_released',
            field=models.BooleanField(default=False),
        ),
    ]
