# Generated by Django 5.1.4 on 2025-01-19 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_assignment_is_private_released'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='external_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AssignmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_grade', models.FloatField(blank=True, null=True)),
                ('private_grade', models.FloatField(blank=True, null=True)),
                ('overall_grade', models.FloatField(blank=True, null=True)),
                ('external_grade', models.FloatField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'assignment')},
            },
        ),
    ]
