# Generated by Django 5.1.4 on 2025-01-19 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_assignment_external_total_assignmentresult'),
        ('runner', '0002_task_head_commit_alter_task_push'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentresult',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='runner.task'),
        ),
    ]
