# Generated by Django 5.1.4 on 2025-03-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_quizaccommodation'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='question_images/')),
                ('question_type', models.CharField(choices=[('WRITTEN_RESPONSE', 'Written Response'), ('CODING', 'Coding'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('CHECKBOX', 'Checkbox')], max_length=16)),
                ('question_id', models.CharField(max_length=256)),
            ],
        ),
    ]
