# Generated by Django 5.1.4 on 2025-03-13 02:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_questionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionimage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
