# Generated by Django 5.1.4 on 2025-01-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_assignmentresult_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenttask',
            name='before_due_date',
            field=models.BooleanField(default=True),
        ),
    ]
