# Generated by Django 5.1.4 on 2025-01-19 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_assignmenttask_before_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='max_grade',
        ),
    ]
