# Generated by Django 5.1.6 on 2025-08-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_assignment_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=50)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
            options={
                'ordering': ['-start', 'slug'],
            },
        ),
    ]
